"""Visualize trained model outputs.

Generates three PNG figures under ``outputs/evaluation/``:
- ``real_samples.png``     : real five-channel samples from the dataset
- ``ae_reconstruction.png``: real vs AE-reconstructed pairs (in original units)
- ``ldm_samples.png``      : five-channel samples generated by the LDM (in original units)

Usage:
    python -m ldm5.visualize --ae_dir outputs/autoencoder/final \
        --unet_dir outputs/latent_diffusion/final --num_samples 6
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
from diffusers import AutoencoderKL, DDPMScheduler, UNet2DModel

from .config import default_config
from .data import build_dataset
from .horizon import soft_horizon_map


def parse_args():
    cfg = default_config()
    p = argparse.ArgumentParser()
    p.add_argument("--data_root", type=str, default=cfg.data.data_root)
    p.add_argument("--output_dir", type=str, default=cfg.train.output_dir)
    p.add_argument("--ae_dir", type=str, default="outputs/autoencoder/final")
    p.add_argument("--unet_dir", type=str, default="outputs/latent_diffusion/final")
    p.add_argument("--num_samples", type=int, default=6)
    p.add_argument("--num_inference_steps", type=int, default=200)
    p.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--save_dir", type=str, default="outputs/evaluation")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--cmap", type=str, default="viridis",
                   help="matplotlib colormap, e.g. viridis (default) / seismic / gray / jet")
    p.add_argument("--skip_ldm", action="store_true", help="Only visualize real/AE reconstruction.")
    return p.parse_args()


def imshow_panel(ax, img: np.ndarray, title: str, cmap: str) -> None:
    """Show a single 2D map with a small colorbar."""
    vmin, vmax = np.percentile(img, [2, 98])
    im = ax.imshow(img, cmap=cmap, vmin=vmin, vmax=vmax)
    ax.set_title(title, fontsize=8)
    ax.set_xticks([])
    ax.set_yticks([])
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.02)


def grid_figure(maps: np.ndarray, channels, row_labels, save_path: Path, suptitle: str, cmap: str) -> None:
    """maps shape: [rows, num_channels, H, W]. Each column = one channel."""
    rows, ncols = maps.shape[:2]
    fig, axes = plt.subplots(rows, ncols, figsize=(2.2 * ncols, 2.2 * rows), squeeze=False)
    for r in range(rows):
        for c in range(ncols):
            title = channels[c] if r == 0 else ""
            imshow_panel(axes[r, c], maps[r, c], title, cmap)
        axes[r, 0].set_ylabel(row_labels[r], fontsize=9)
    fig.suptitle(suptitle, fontsize=11)
    fig.tight_layout()
    fig.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {save_path}")


@torch.no_grad()
def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)

    cfg = default_config()
    cfg.data.data_root = args.data_root
    dataset, _stats = build_dataset(cfg.data, stats_path=Path(args.output_dir) / "norm_stats.json")
    channels = cfg.data.channels
    print(f"Dataset: {len(dataset)} samples, channels={channels}")

    # ---- pick real samples ----
    idxs = np.random.choice(len(dataset), size=args.num_samples, replace=False)
    real_norm = torch.stack([dataset[int(i)] for i in idxs])  # [N,5,H,W], z-normalized
    real_orig = dataset.denormalize(real_norm)  # back to original physical units

    grid_figure(
        real_orig.cpu().numpy(),
        channels=channels,
        row_labels=[f"sample {int(i)}" for i in idxs],
        save_path=save_dir / "real_samples.png",
        suptitle="Real five-channel samples (original units)",
        cmap=args.cmap,
    )

    # ---- AE reconstruction ----
    ae = AutoencoderKL.from_pretrained(args.ae_dir).to(args.device).eval()
    x = real_norm.to(args.device)
    recon_norm = ae.decode(ae.encode(x).latent_dist.mode()).sample
    recon_orig = dataset.denormalize(recon_norm.cpu())

    real_horizon = soft_horizon_map(real_norm).cpu()
    recon_horizon = soft_horizon_map(recon_norm.cpu())
    horizon_error = (real_horizon - recon_horizon).abs()

    # Interleave [real, recon] row-wise per channel.
    pair_maps = []
    pair_labels = []
    for i in range(args.num_samples):
        pair_maps.append(real_orig[i].numpy())
        pair_maps.append(recon_orig[i].numpy())
        pair_labels.append(f"#{int(idxs[i])} real")
        pair_labels.append(f"#{int(idxs[i])} recon")
    pair_maps = np.stack(pair_maps, axis=0)  # [2N,5,H,W]
    grid_figure(
        pair_maps,
        channels=channels,
        row_labels=pair_labels,
        save_path=save_dir / "ae_reconstruction.png",
        suptitle="Autoencoder reconstruction: real vs recon (original units)",
        cmap=args.cmap,
    )

    horizon_maps = []
    horizon_labels = []
    for i in range(args.num_samples):
        horizon_maps.append(real_horizon[i].numpy())
        horizon_maps.append(recon_horizon[i].numpy())
        horizon_maps.append(horizon_error[i].numpy())
        horizon_labels.append(f"#{int(idxs[i])} real")
        horizon_labels.append(f"#{int(idxs[i])} recon")
        horizon_labels.append(f"#{int(idxs[i])} |err|")
    grid_figure(
        np.stack(horizon_maps, axis=0),
        channels=["horizon"],
        row_labels=horizon_labels,
        save_path=save_dir / "ae_horizon_reconstruction.png",
        suptitle="Soft horizon maps: real vs reconstruction",
        cmap="magma",
    )

    gen_orig = None
    if not args.skip_ldm:
        # ---- LDM samples ----
        unet = UNet2DModel.from_pretrained(args.unet_dir).to(args.device).eval()
        scheduler = DDPMScheduler(num_train_timesteps=1000, prediction_type="epsilon")
        scheduler.set_timesteps(args.num_inference_steps)
        shape = (args.num_samples, unet.config.in_channels,
                 unet.config.sample_size, unet.config.sample_size)
        latents = torch.randn(shape, device=args.device)
        for t in scheduler.timesteps:
            pred = unet(latents, t).sample
            latents = scheduler.step(pred, t, latents).prev_sample
        gen_norm = ae.decode(latents).sample.cpu()
        gen_orig = dataset.denormalize(gen_norm)

        grid_figure(
            gen_orig.numpy(),
            channels=channels,
            row_labels=[f"gen #{i + 1}" for i in range(args.num_samples)],
            save_path=save_dir / "ldm_samples.png",
            suptitle=f"Latent DDPM samples (steps={args.num_inference_steps}, original units)",
            cmap=args.cmap,
        )

    arrays = {
        "real": real_orig.cpu().numpy(),
        "recon": recon_orig.cpu().numpy(),
        "real_horizon": real_horizon.numpy(),
        "recon_horizon": recon_horizon.numpy(),
        "horizon_error": horizon_error.numpy(),
        "channels": np.array(channels),
        "indices": np.array(idxs),
    }
    if gen_orig is not None:
        arrays["generated"] = gen_orig.cpu().numpy()
    np.savez(save_dir / "visualize_arrays.npz", **arrays)
    print(f"Saved raw arrays to {save_dir / 'visualize_arrays.npz'}")


if __name__ == "__main__":
    main()
